// Code generated by "stringer -type=UOM"; DO NOT EDIT.

package isy

import "fmt"

const _UOM_name = "UOMUnknownUOMAmpereUOMBooleanUOMBTUPerHourUOMCelsiusUOMCentimeterUOMCubicFeetUOMCubicFeetPerMinuteUOMCubicMeterUOMDayUOMDaysUOMDeadboltStatusUOMDecibelUOMDecibelAUOMDegreeUOMDoorLockStatusUOMEuropeanMacroseismicUOMFahrenheitUOMFeetUOMHourUOMHoursUOMAbsoluteHumidityUOMRelativeHumidityUOMInchesOfMercuryUOMInchesPerHourUOMIndexUOMKelvinUOMKeywordUOMKilogramUOMKilovoltUOMKilowattUOMKilopascalUOMKilometersPerHourUOMKilowattHourUOMLieduUOMLiterUOMLuxUOMMercalliUOMMeterUOMCubicMetersPerHourUOMMetersPerSecondUOMMilliampUOMMillisecondUOMMillivoltUOMMinuteUOMDurationInMinutesUOMMillimetersPerHOurUOMMonthUOMMilesPerHourUOMMetersPerSecond2UOMOhmUOMPercentUOMPoundUOMPowerFactorUOMPartsPerMillionUOMPulseCountUOMRawValueUOMSecondUOMDurationInSecondsUOMSeimensPerMeterUOMBodyWaveMagnituteScaleUOMRichterScaleUOMMomentMagnitudeScaleUOMSurfaceWaveMagnitudeScaleUOMShindoUOMSMLUOMThermostatStateUOMThermostatModeUOMThermostatFanModeUOMUSGallonUOMUserNumberUOMUVIndexUOMVoltUOMWattUOMWattsPerSquareMeterUOMWeekdayUOMWindDirectionDegreesUOMYearUOM100OnUOM100ClosedUOMThermostatFanRunStateUOMThermostatFanModeOverrideUOMMillimeterUOMKilometerUOMSecureModeUOMElectricalResistivityUOMKiloohmUOMCubicMetersPerCubicMeterUOMWaterActivityUOMRotationsPerMinuteUOMHertzUOMDegreesFromNorthPoleUOMDegreesFromSouthPoleUOMPowerManagementAlarmStatusUOMApplianceAlarmStatusUOMHomeHealthAlarmStatusUOMVOCLevelUOMBarrierStatusUOMInsteonThermostatModeUOMInsteonThermostatFanModeUOMByteLevelUOMDegreesTimesTwoUOMKilowattSecondUOMDollarUOMCentUOMInchUOMMillimetersPerDay"

var _UOM_index = [...]uint16{0, 10, 19, 29, 42, 52, 65, 77, 98, 111, 117, 124, 141, 151, 162, 171, 188, 211, 224, 231, 238, 246, 265, 284, 302, 318, 326, 335, 345, 356, 367, 378, 391, 411, 426, 434, 442, 448, 459, 467, 488, 506, 517, 531, 543, 552, 572, 593, 601, 616, 635, 641, 651, 659, 673, 691, 704, 715, 724, 744, 762, 787, 802, 825, 853, 862, 868, 886, 903, 923, 934, 947, 957, 964, 971, 993, 1003, 1026, 1033, 1041, 1053, 1077, 1105, 1118, 1130, 1143, 1167, 1177, 1204, 1220, 1241, 1249, 1272, 1295, 1324, 1347, 1371, 1382, 1398, 1422, 1449, 1461, 1479, 1496, 1505, 1512, 1519, 1539}

func (i UOM) String() string {
	if i < 0 || i >= UOM(len(_UOM_index)-1) {
		return fmt.Sprintf("UOM(%d)", i)
	}
	return _UOM_name[_UOM_index[i]:_UOM_index[i+1]]
}
